parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Core/Domain/*'
            - '../src/Core/UseCase/*/*Request.php'

    App\Controller\:
        resource: '../src/Controller'
        exclude: '../src/Controller/Presenter/*'
        tags: [ 'controller.service_arguments' ]

when@test:
    services:
        App\Tests\Gateway\:
            resource: '../tests/Gateway/*'
            autowire: true
            autoconfigure: true
            public: true

        App\Core\Gateway\DetailedMovieRetriever:
            alias: 'App\Tests\Gateway\InMemoryDetailedMovieRetriever'
        App\Core\Gateway\GenderFinder:
            alias: 'App\Tests\Gateway\InMemoryGenderFinder'
        App\Core\Gateway\ListedMovieFinder:
            alias: 'App\Tests\Gateway\InMemoryListedMovieFinder'